### ISSUE TITLE
Crouching instant reloading the gun 

### ISSUE THREAD

**Issue by sam1475** [qbcore-framework/qb-weapons#188]
**Describe the bug**
Crouching instant reloading the gun. Spam R and Crouch to autofire a one round gun.

**To Reproduce**
1. Press R
2. Crouch
3. Fire
4. Repeat

**Expected behavior**
Cancels the reload with the anim cancel or reloads still
**Screenshots**

[If applicable, add screenshots to help explain your problem.
](https://gyazo.com/3205db22c8996bc91d57eb5d49b17f98)

**Questions (please complete the following information):**
 - When you last updated: Today
 - Are you using custom resource? No
 - Have you renamed `qb-` to something custom? No

**Additional context**

**Comment by MilyonJames** [comment]
This can be fixed by adding `not IsPedReloading(ped)` to [qb-smallresources/client/crouchphone.lua#L35](https://github.com/qbcore-framework/qb-smallresources/blob/d06d5c104552b807e1d0bd7cfa225103bb93ea3e/client/crouchprone.lua#L35)
This would look like that:
`lua
if not IsPedSittingInAnyVehicle(ped) and not IsPedFalling(ped) and not IsPedSwimming(ped) and not IsPedSwimmingUnderWater(ped) and not IsPauseMenuActive() and not IsPedReloading(ped) then
`

I guess this issue should be posted to [qb-smallresources](https://github.com/qbcore-framework/qb-smallresources/issues).
