### ISSUE TITLE
script error main.lua228 attemt to index a nil value

### ISSUE THREAD

**Issue by sabotage93thctv** [qbcore-framework/qb-weapons#190]
hi we are a bit stuck been adding a new weapons pack we keep getting the same error and when i look at our lua in the same place i cant see anything that may need changed 

![Screenshot 2024-06-05 014110](https://github.com/qbcore-framework/qb-weapons/assets/152351449/aded1695-a865-448a-8957-1d82d0627d79)

**Comment by t0r3tto** [comment]
not a bug/not a support channel use discord forums

**Comment by Scartane** [comment]
Hey,
You break the config file when you add your new entries in it (probably miss to add a comma at the end of the line before or something like that.
You should do `restart qb-weapons` and check the log when the script start in f8 console or server console, you will see the line number where the problem is located in your config file.
But it's not related to the script actually.
